global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['localhost:8080']
    basic_auth:
      username: admin
      password: admin
   
  - job_name: 'node'
    metrics_path: '/node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'capstone'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3000']
