apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 80
    nodePort: 30001
  selector:
    app: CRM
---
apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  type: NodePort
  ports:
  - targetPort: 3000
    port: 81
    nodePort: 30002
  selector:
    app: CRM1
